### ISSUE TITLE
Install files for v0.1.2 still run the v0.1 launcher, bug for path with spaces still present

### ISSUE THREAD

**Issue by joeygreco1985** [HFTSRedux/TS2Redux#8] opened 2021-11-08 21:16 UTC
Just downloaded the most recent release but I still get the same crash when I try option 2 (my path has spaces). The launcher references v0.1 as well

**Comment by GoTeamScotch** [comment] 2021-11-08 22:09
Duplicate of #2

**Comment by GoTeamScotch** [comment] 2022-01-18 16:45
A new version of the installer has been released, version 0.2.6, which should fix issues like this when installing the mod. It uses an entirely new method of installing files than in previous versions. Please download and use the new version. Report any issues you encounter. Download: [TS2 Redux v0.2.6](https://github.com/HFTSRedux/TS2Redux/releases)

Marking this issue as closed. Feel free to reply if the problem persists.

**Closed by GoTeamScotch** 2022-01-18 16:45 UTC
